### ISSUE TITLE
Instant validations

### ISSUE THREAD

**Issue by jarnheimer** [proxify-ab/vue-forms#2]
> Show positive messages as soon as possible to give the user good feedback!

![screen shot 2017-10-11 at 17 12 46](https://user-images.githubusercontent.com/1903647/31449540-77765e88-aea7-11e7-8566-6216c2f67ce2.png)

**Instant validation**

 - [ ] The form is always "normal" when the user hasn't touched it. After typing or clicking, it receives the class `has-success` or `has-error`.
 - [x] When the user are *finished* typing, the `has-error` class is applied if the input is `required` and doesn't meet any of the three criteria. For example, if the users should type his name, `has-error` is applied when the user has entered *"812093812"* and exits the input.
 - [x] The class `has-success` can be applied as soon as the form is correct. For example, if the user should type his name, `has-success` is applied when the user has entered *"Vi"* which can be a correct name.

**Error messages**
 - [x] It would be nice if we could, [just like in Laravel](https://laravel.com/docs/5.5/validation#custom-error-messages), have unique error messages for an input and validation.
 - [x] For *input[type=text]* the error message is shown in the <p> with the class *helper-text*.

**The following instant validations would we like to have:**

 - [x] accepted
 - [x] email
 - [x] required
 - [x] name
 - [x] digit
 - [ ] phone number
 - [x] min (the number is higher or equal to...)
 - [x] max (the number is lower or equal to...)

Of course, there are more that would be nice https://laravel.com/docs/5.5/validation#rule-active-url . But these are the most important once.

**Comment by jarnheimer** [comment]
Maybe it would be nice take some code from this?
https://m.dotdev.co/form-validation-using-vue-js-2-35abd6b18c5d

**Comment by laravel-vesuvius** [comment]
Could you please review my code? I'm not sure I'm moving in the right direction.

**Comment by jarnheimer** [comment]
You are definitely in the right direction. But please take a look at this again:
>The form is always "normal" when the user hasn't touched it. After typing or clicking, it receives the class has-success or has-error.

**Comment by jarnheimer** [comment]
@lhaynes23 will provide you with a few examples

**Comment by lhaynes23** [comment]
Hi @laravel-vesuvius,

I did post this in the one js-file issue thread but thought I would here as well as it makes more sense perhaps in this issue thread. I'm sure you've already seen it but here it is again in case:

Here are some examples to show you what we mean with the instant validations and how the vue forms should work.

<img width="1160" alt="screen shot 2017-10-25 at 11 33 41" src="https://user-images.githubusercontent.com/26088054/31991611-77580790-b978-11e7-9157-ae79440759a7.png">

<img width="596" alt="screen shot 2017-10-25 at 11 33 47" src="https://user-images.githubusercontent.com/26088054/31991624-7e64f796-b978-11e7-8e34-ff334a631e0f.png">

<img width="631" alt="screen shot 2017-10-25 at 11 34 02" src="https://user-images.githubusercontent.com/26088054/31991637-82f3f528-b978-11e7-8aee-4883b5d1909e.png">

<img width="665" alt="screen shot 2017-10-25 at 11 34 07" src="https://user-images.githubusercontent.com/26088054/31991648-887d6ef2-b978-11e7-96b1-60fe09306e3e.png">

Let us know if you have any questions.

**Comment by lhaynes23** [comment]
Hi @laravel-vesuvius 

Nice to see the examples you've been doing!

I made a recording below regarding some issues with the error message on lastName. Firstly it is showing .has-error when it shouldn't and secondly it is not showing the error message when there is an error.

Also the radio buttons seem to not be working as smoothly as they might. Mostly the one with the value 'female' I believe.

![example.html validations](http://g.recordit.co/tgEd8aMooO.gif)
