### ISSUE TITLE
One.js-file structure with three examples

### ISSUE THREAD

**Issue by jarnheimer** [proxify-ab/vue-forms#7]
The `vue-forms` should basically be an add-on to Vue.js which help us to render forms quickly.

`<script src="/js/vue-forms-by-proxify.js"></script>` in its context:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>

     <div id="form">

       <textarea-box type="email" name="email" label="Input email" rules="required|email" v-model="obj.email"></textarea-box>

    </div>

     <script src="https://unpkg.com/vue"></script>
     <script src="/js/vue-forms-by-proxify.js"></script>

<script>

var app = new Vue({
  el: '#form',
  data: {
    [...]
  },
   [...]
})

</script>



  </body>
</html>
```

**Comment by jarnheimer** [comment]
Can you please create three example files (not compiled using npm) using the html above @laravel-vesuvius

**Comment by laravel-vesuvius** [comment]
I do not really understand exactly which examples you would like to see?

**Comment by jarnheimer** [comment]
You can start with this form:

- First name
- Last name
- Gender (radio with male or female)
- Age (select)

@lhaynes23 Is about to create more.

**Comment by laravel-vesuvius** [comment]
I have created a form, check please i have done everything right?

**Comment by lhaynes23** [comment]
Hi @laravel-vesuvius,

Here are some examples to show you what we mean with the instant validations and how the vue forms should work.

<img width="1160" alt="screen shot 2017-10-25 at 11 33 41" src="https://user-images.githubusercontent.com/26088054/31991611-77580790-b978-11e7-9157-ae79440759a7.png">

<img width="596" alt="screen shot 2017-10-25 at 11 33 47" src="https://user-images.githubusercontent.com/26088054/31991624-7e64f796-b978-11e7-8e34-ff334a631e0f.png">

<img width="631" alt="screen shot 2017-10-25 at 11 34 02" src="https://user-images.githubusercontent.com/26088054/31991637-82f3f528-b978-11e7-8aee-4883b5d1909e.png">

<img width="665" alt="screen shot 2017-10-25 at 11 34 07" src="https://user-images.githubusercontent.com/26088054/31991648-887d6ef2-b978-11e7-96b1-60fe09306e3e.png">

Let us know if you have any questions.
